export interface CategoryPresetItem {
  divisionGroup: "OPEN" | "PELAJAR" | "DISABILITAS" | "VETERAN" | "BOB";
  subGroup?: string;
  name: string;
  categoryType: "KATA_INDIVIDUAL" | "KATA_TEAM" | "KUMITE_INDIVIDUAL" | "KUMITE_TEAM";
  gender: "MALE" | "FEMALE" | "MIXED";
  minAge?: number | null;
  maxAge?: number | null;
  minBirthDate?: string | null;
  maxBirthDate?: string | null;
  minWeight?: number | null;
  maxWeight?: number | null;
  defaultFee?: number;
}

export const TOURNAMENT_CATEGORY_PRESETS: CategoryPresetItem[] = [
  // ==================================================
  // 1. KATEGORI TERBUKA / OPEN
  // ==================================================
  // A. PRA USIA DINI (Kelahiran 2019-2020 / Usia 6-7 Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Usia Dini (6-7 Thn / 2019-2020)",
    name: "Pra Usia Dini - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 6,
    maxAge: 7,
    minBirthDate: "2019-01-01",
    maxBirthDate: "2020-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Usia Dini (6-7 Thn / 2019-2020)",
    name: "Pra Usia Dini - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 6,
    maxAge: 7,
    minBirthDate: "2019-01-01",
    maxBirthDate: "2020-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Usia Dini (6-7 Thn / 2019-2020)",
    name: "Pra Usia Dini - Kumite Putra -20 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 6,
    maxAge: 7,
    minBirthDate: "2019-01-01",
    maxBirthDate: "2020-12-31",
    maxWeight: 20,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Usia Dini (6-7 Thn / 2019-2020)",
    name: "Pra Usia Dini - Kumite Putra +20 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 6,
    maxAge: 7,
    minBirthDate: "2019-01-01",
    maxBirthDate: "2020-12-31",
    minWeight: 20.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Usia Dini (6-7 Thn / 2019-2020)",
    name: "Pra Usia Dini - Kumite Putri -20 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 6,
    maxAge: 7,
    minBirthDate: "2019-01-01",
    maxBirthDate: "2020-12-31",
    maxWeight: 20,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Usia Dini (6-7 Thn / 2019-2020)",
    name: "Pra Usia Dini - Kumite Putri +20 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 6,
    maxAge: 7,
    minBirthDate: "2019-01-01",
    maxBirthDate: "2020-12-31",
    minWeight: 20.1,
  },

  // B. USIA DINI (Kelahiran 2017-2018 / Usia 8-9 Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kata Beregu Putra",
    categoryType: "KATA_TEAM",
    gender: "MALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kata Beregu Putri",
    categoryType: "KATA_TEAM",
    gender: "FEMALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kumite Putra -25 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    maxWeight: 25,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kumite Putra -30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    minWeight: 25.1,
    maxWeight: 30,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kumite Putra +30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    minWeight: 30.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kumite Putri -25 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    maxWeight: 25,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kumite Putri -30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    minWeight: 25.1,
    maxWeight: 30,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Usia Dini (8-9 Thn / 2017-2018)",
    name: "Usia Dini - Kumite Putri +30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 8,
    maxAge: 9,
    minBirthDate: "2017-01-01",
    maxBirthDate: "2018-12-31",
    minWeight: 30.1,
  },

  // C. PRA PEMULA (Kelahiran 2015-2016 / Usia 10-11 Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kata Beregu Putra",
    categoryType: "KATA_TEAM",
    gender: "MALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kata Beregu Putri",
    categoryType: "KATA_TEAM",
    gender: "FEMALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kumite Putra -30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    maxWeight: 30,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kumite Putra -35 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    minWeight: 30.1,
    maxWeight: 35,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kumite Putra -40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    minWeight: 35.1,
    maxWeight: 40,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kumite Putra +40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    minWeight: 40.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kumite Putri -30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    maxWeight: 30,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kumite Putri -35 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    minWeight: 30.1,
    maxWeight: 35,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pra Pemula (10-11 Thn / 2015-2016)",
    name: "Pra Pemula - Kumite Putri +35 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 10,
    maxAge: 11,
    minBirthDate: "2015-01-01",
    maxBirthDate: "2016-12-31",
    minWeight: 35.1,
  },

  // D. PEMULA (Kelahiran 2013-2014 / Usia 12-13 Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kata Beregu Putra",
    categoryType: "KATA_TEAM",
    gender: "MALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kata Beregu Putri",
    categoryType: "KATA_TEAM",
    gender: "FEMALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putra -35 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    maxWeight: 35,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putra -40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    minWeight: 35.1,
    maxWeight: 40,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putra -45 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    minWeight: 40.1,
    maxWeight: 45,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putra -50 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    minWeight: 45.1,
    maxWeight: 50,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putra +50 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    minWeight: 50.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putri -35 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    maxWeight: 35,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putri -40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    minWeight: 35.1,
    maxWeight: 40,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putri -45 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    minWeight: 40.1,
    maxWeight: 45,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Pemula (12-13 Thn / 2013-2014)",
    name: "Pemula - Kumite Putri +45 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 12,
    maxAge: 13,
    minBirthDate: "2013-01-01",
    maxBirthDate: "2014-12-31",
    minWeight: 45.1,
  },

  // E. KADET (Kelahiran 2011-2012 / Usia 14-15 Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kata Beregu Putra",
    categoryType: "KATA_TEAM",
    gender: "MALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kata Beregu Putri",
    categoryType: "KATA_TEAM",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putra -52 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    maxWeight: 52,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putra -57 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    minWeight: 52.1,
    maxWeight: 57,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putra -63 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    minWeight: 57.1,
    maxWeight: 63,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putra -70 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    minWeight: 63.1,
    maxWeight: 70,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putra +70 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    minWeight: 70.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putri -47 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    maxWeight: 47,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putri -54 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    minWeight: 47.1,
    maxWeight: 54,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putri -61 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    minWeight: 54.1,
    maxWeight: 61,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kadet (14-15 Thn / 2011-2012)",
    name: "Kadet - Kumite Putri +61 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 15,
    minBirthDate: "2011-01-01",
    maxBirthDate: "2012-12-31",
    minWeight: 61.1,
  },

  // F. JUNIOR (Kelahiran 2009-2010 / Usia 16-17 Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kata Beregu Putra",
    categoryType: "KATA_TEAM",
    gender: "MALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kata Beregu Putri",
    categoryType: "KATA_TEAM",
    gender: "FEMALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putra -55 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    maxWeight: 55,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putra -61 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 55.1,
    maxWeight: 61,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putra -68 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 61.1,
    maxWeight: 68,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putra -76 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 68.1,
    maxWeight: 76,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putra +76 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 76.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putri -48 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    maxWeight: 48,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putri -53 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 48.1,
    maxWeight: 53,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putri -59 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 53.1,
    maxWeight: 59,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putri -66 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 59.1,
    maxWeight: 66,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Junior (16-17 Thn / 2009-2010)",
    name: "Junior - Kumite Putri +66 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 16,
    maxAge: 17,
    minBirthDate: "2009-01-01",
    maxBirthDate: "2010-12-31",
    minWeight: 66.1,
  },

  // G. U-21 (Kelahiran 2006-2008 / Usia 18-20 Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kata Beregu Putra",
    categoryType: "KATA_TEAM",
    gender: "MALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kata Beregu Putri",
    categoryType: "KATA_TEAM",
    gender: "FEMALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putra -55 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    maxWeight: 55,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putra -61 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 55.1,
    maxWeight: 61,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putra -68 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 61.1,
    maxWeight: 68,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putra -76 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 68.1,
    maxWeight: 76,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putra +76 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 76.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putri -48 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    maxWeight: 48,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putri -53 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 48.1,
    maxWeight: 53,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putri -59 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 53.1,
    maxWeight: 59,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putri -66 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 59.1,
    maxWeight: 66,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "U-21 (18-20 Thn / 2006-2008)",
    name: "U-21 - Kumite Putri +66 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 18,
    maxAge: 20,
    minBirthDate: "2006-01-01",
    maxBirthDate: "2008-12-31",
    minWeight: 66.1,
  },

  // H. SENIOR (Kelahiran 2005 & Sebelumnya / Usia 21+ Tahun)
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kata Beregu Putra",
    categoryType: "KATA_TEAM",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kata Beregu Putri",
    categoryType: "KATA_TEAM",
    gender: "FEMALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    defaultFee: 250000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putra -55 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    maxWeight: 55,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putra -60 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 55.1,
    maxWeight: 60,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putra -67 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 60.1,
    maxWeight: 67,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putra -75 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 67.1,
    maxWeight: 75,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putra -84 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 75.1,
    maxWeight: 84,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putra +84 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 84.1,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putri -50 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    maxWeight: 50,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putri -55 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 50.1,
    maxWeight: 55,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putri -61 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 55.1,
    maxWeight: 61,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putri -68 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 61.1,
    maxWeight: 68,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Senior (21+ Thn / 2005 & Sblm)",
    name: "Senior - Kumite Putri +68 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 21,
    maxBirthDate: "2005-12-31",
    minWeight: 68.1,
  },

  // I. KUMITE BEREGU TERBUKA
  {
    divisionGroup: "OPEN",
    subGroup: "Kumite Beregu Terbuka",
    name: "Kumite Beregu Putra Kadet-Junior",
    categoryType: "KUMITE_TEAM",
    gender: "MALE",
    minAge: 14,
    maxAge: 17,
    defaultFee: 300000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kumite Beregu Terbuka",
    name: "Kumite Beregu Putri Kadet-Junior",
    categoryType: "KUMITE_TEAM",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 17,
    defaultFee: 300000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kumite Beregu Terbuka",
    name: "Kumite Beregu Putra U21-Senior",
    categoryType: "KUMITE_TEAM",
    gender: "MALE",
    minAge: 18,
    defaultFee: 300000,
  },
  {
    divisionGroup: "OPEN",
    subGroup: "Kumite Beregu Terbuka",
    name: "Kumite Beregu Putri U21-Senior",
    categoryType: "KUMITE_TEAM",
    gender: "FEMALE",
    minAge: 18,
    defaultFee: 300000,
  },

  // ==================================================
  // 2. KATEGORI PELAJAR
  // ==================================================
  // A. PELAJAR TK
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar TK",
    name: "Pelajar TK Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar TK",
    name: "Pelajar TK Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar TK",
    name: "Pelajar TK Kumite Perorangan Putra Bebas",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar TK",
    name: "Pelajar TK Kumite Perorangan Putri Bebas",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
  },

  // B. PELAJAR SD KELAS 1-3
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 1-3",
    name: "Pelajar SD Kelas 1-3 Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 1-3",
    name: "Pelajar SD Kelas 1-3 Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 1-3",
    name: "Pelajar SD Kelas 1-3 Kumite Perorangan Putra -25 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    maxWeight: 25,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 1-3",
    name: "Pelajar SD Kelas 1-3 Kumite Perorangan Putra +25 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minWeight: 25.1,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 1-3",
    name: "Pelajar SD Kelas 1-3 Kumite Perorangan Putri -25 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    maxWeight: 25,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 1-3",
    name: "Pelajar SD Kelas 1-3 Kumite Perorangan Putri +25 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minWeight: 25.1,
  },

  // C. PELAJAR SD KELAS 4-6
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 4-6",
    name: "Pelajar SD Kelas 4-6 Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 4-6",
    name: "Pelajar SD Kelas 4-6 Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 4-6",
    name: "Pelajar SD Kelas 4-6 Kumite Perorangan Putra -30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    maxWeight: 30,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 4-6",
    name: "Pelajar SD Kelas 4-6 Kumite Perorangan Putra +30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minWeight: 30.1,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 4-6",
    name: "Pelajar SD Kelas 4-6 Kumite Perorangan Putri -30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    maxWeight: 30,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SD Kelas 4-6",
    name: "Pelajar SD Kelas 4-6 Kumite Perorangan Putri +30 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minWeight: 30.1,
  },

  // D. PELAJAR SMP / MTs
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMP / MTs",
    name: "Pelajar SMP/MTs Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMP / MTs",
    name: "Pelajar SMP/MTs Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMP / MTs",
    name: "Pelajar SMP/MTs Kumite Perorangan Putra -40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    maxWeight: 40,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMP / MTs",
    name: "Pelajar SMP/MTs Kumite Perorangan Putra +40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minWeight: 40.1,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMP / MTs",
    name: "Pelajar SMP/MTs Kumite Perorangan Putri -40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    maxWeight: 40,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMP / MTs",
    name: "Pelajar SMP/MTs Kumite Perorangan Putri +40 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minWeight: 40.1,
  },

  // E. PELAJAR SMA / SMK / MA
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMA / SMK / MA",
    name: "Pelajar SMA/SMK/MA Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMA / SMK / MA",
    name: "Pelajar SMA/SMK/MA Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMA / SMK / MA",
    name: "Pelajar SMA/SMK/MA Kumite Perorangan Putra -50 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    maxWeight: 50,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMA / SMK / MA",
    name: "Pelajar SMA/SMK/MA Kumite Perorangan Putra +50 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minWeight: 50.1,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMA / SMK / MA",
    name: "Pelajar SMA/SMK/MA Kumite Perorangan Putri -50 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    maxWeight: 50,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar SMA / SMK / MA",
    name: "Pelajar SMA/SMK/MA Kumite Perorangan Putri +50 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minWeight: 50.1,
  },

  // F. PELAJAR MAHASISWA / UMUM
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar Mahasiswa / Umum",
    name: "Pelajar Mahasiswa/Umum Kata Perorangan Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar Mahasiswa / Umum",
    name: "Pelajar Mahasiswa/Umum Kata Perorangan Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar Mahasiswa / Umum",
    name: "Pelajar Mahasiswa/Umum Kumite Perorangan Putra -67 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    maxWeight: 67,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar Mahasiswa / Umum",
    name: "Pelajar Mahasiswa/Umum Kumite Perorangan Putra +67 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minWeight: 67.1,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar Mahasiswa / Umum",
    name: "Pelajar Mahasiswa/Umum Kumite Perorangan Putri -61 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    maxWeight: 61,
  },
  {
    divisionGroup: "PELAJAR",
    subGroup: "Pelajar Mahasiswa / Umum",
    name: "Pelajar Mahasiswa/Umum Kumite Perorangan Putri +61 kg",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minWeight: 61.1,
  },

  // ==================================================
  // 3. KATEGORI EKSEBISI DISABILITAS
  // ==================================================
  {
    divisionGroup: "DISABILITAS",
    subGroup: "Eksebisi Disabilitas",
    name: "Kata Perorangan Putra Disabilitas Rungu/Wicara",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "DISABILITAS",
    subGroup: "Eksebisi Disabilitas",
    name: "Kata Perorangan Putra Disabilitas Daksa",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "DISABILITAS",
    subGroup: "Eksebisi Disabilitas",
    name: "Kata Perorangan Putra Disabilitas Grahita",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
  },
  {
    divisionGroup: "DISABILITAS",
    subGroup: "Eksebisi Disabilitas",
    name: "Kata Perorangan Putri Disabilitas Rungu/Wicara",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "DISABILITAS",
    subGroup: "Eksebisi Disabilitas",
    name: "Kata Perorangan Putri Disabilitas Daksa",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },
  {
    divisionGroup: "DISABILITAS",
    subGroup: "Eksebisi Disabilitas",
    name: "Kata Perorangan Putri Disabilitas Grahita",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
  },

  // ==================================================
  // 4. KATEGORI VETERAN
  // ==================================================
  // A. KATA PERORANGAN VETERAN
  {
    divisionGroup: "VETERAN",
    subGroup: "Kata Perorangan Veteran",
    name: "Kata Perorangan Putra 30-40 Tahun",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 30,
    maxAge: 40,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kata Perorangan Veteran",
    name: "Kata Perorangan Putra 40-50 Tahun",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 40,
    maxAge: 50,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kata Perorangan Veteran",
    name: "Kata Perorangan Putra +50 Tahun",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 50,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kata Perorangan Veteran",
    name: "Kata Perorangan Putri 30-40 Tahun",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 30,
    maxAge: 40,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kata Perorangan Veteran",
    name: "Kata Perorangan Putri 40-50 Tahun",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 40,
    maxAge: 50,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kata Perorangan Veteran",
    name: "Kata Perorangan Putri +50 Tahun",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 50,
  },

  // B. KUMITE PERORANGAN VETERAN
  {
    divisionGroup: "VETERAN",
    subGroup: "Kumite Perorangan Veteran",
    name: "Kumite Perorangan Putra 30-40 Tahun",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 30,
    maxAge: 40,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kumite Perorangan Veteran",
    name: "Kumite Perorangan Putra 40-50 Tahun",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 40,
    maxAge: 50,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kumite Perorangan Veteran",
    name: "Kumite Perorangan Putra +50 Tahun",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 50,
  },
  {
    divisionGroup: "VETERAN",
    subGroup: "Kumite Perorangan Veteran",
    name: "Kumite Perorangan Putri +50 Tahun",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 50,
  },

  // ==================================================
  // 5. KATEGORI BEST OF THE BEST (BOB)
  // ==================================================
  {
    divisionGroup: "BOB",
    subGroup: "Best of the Best",
    name: "BOB Kumite Kadet - Junior Putra",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    maxAge: 17,
    defaultFee: 200000,
  },
  {
    divisionGroup: "BOB",
    subGroup: "Best of the Best",
    name: "BOB Kumite Kadet - Junior Putri",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 14,
    maxAge: 17,
    defaultFee: 200000,
  },
  {
    divisionGroup: "BOB",
    subGroup: "Best of the Best",
    name: "BOB Kumite U21 - Senior Putra",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "MALE",
    minAge: 18,
    defaultFee: 200000,
  },
  {
    divisionGroup: "BOB",
    subGroup: "Best of the Best",
    name: "BOB Kumite U21 - Senior Putri",
    categoryType: "KUMITE_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 18,
    defaultFee: 200000,
  },
  {
    divisionGroup: "BOB",
    subGroup: "Best of the Best",
    name: "BOB Kata Kadet - Senior Putra",
    categoryType: "KATA_INDIVIDUAL",
    gender: "MALE",
    minAge: 14,
    defaultFee: 200000,
  },
  {
    divisionGroup: "BOB",
    subGroup: "Best of the Best",
    name: "BOB Kata Kadet - Senior Putri",
    categoryType: "KATA_INDIVIDUAL",
    gender: "FEMALE",
    minAge: 14,
    defaultFee: 200000,
  },
];

export function deriveAgeCategoryLabel(
  categoryName: string = "",
  minAge?: number | null,
  maxAge?: number | null,
  birthDate?: string | Date | null
): string {
  const name = (categoryName || "").trim();
  const upper = name.toUpperCase();

  // 1. Check keyword in category name first
  if (upper.includes("PRA USIA DINI") || upper.includes("PRA-USIA DINI")) return "Pra Usia Dini (6-7 Thn)";
  if (upper.includes("USIA DINI")) return "Usia Dini (8-9 Thn)";
  if (upper.includes("PRA PEMULA") || upper.includes("PRA-PEMULA")) return "Pra Pemula (10-11 Thn)";
  if (upper.includes("PEMULA")) return "Pemula (12-13 Thn)";
  if (upper.includes("KADET")) return "Kadet (14-15 Thn)";
  if (upper.includes("JUNIOR")) return "Junior (16-17 Thn)";
  if (upper.includes("U-21") || upper.includes("U21") || upper.includes("UNDER 21") || upper.includes("UNDER-21")) return "U-21 (18-20 Thn)";
  if (upper.includes("SENIOR")) return "Senior (21+ Thn)";
  if (upper.includes("PELAJAR TK") || upper.includes("TK ")) return "Pelajar TK";
  if (upper.includes("SD KELAS 1-3") || upper.includes("SD 1-3")) return "Pelajar SD (1-3)";
  if (upper.includes("SD KELAS 4-6") || upper.includes("SD 4-6") || upper.includes("PELAJAR SD")) return "Pelajar SD (4-6)";
  if (upper.includes("SMP") || upper.includes("MTS")) return "Pelajar SMP / MTs";
  if (upper.includes("SMA") || upper.includes("SMK") || upper.includes("MA ")) return "Pelajar SMA / SMK / MA";
  if (upper.includes("MAHASISWA") || upper.includes("UMUM")) return "Pelajar Mahasiswa / Umum";
  if (upper.includes("DISABILITAS") || upper.includes("RUNGU") || upper.includes("DAKSA") || upper.includes("GRAHITA")) return "Eksebisi Disabilitas";
  if (upper.includes("VETERAN")) {
    if (upper.includes("30-40")) return "Veteran (30-40 Thn)";
    if (upper.includes("40-50")) return "Veteran (40-50 Thn)";
    if (upper.includes("+50") || upper.includes("50+")) return "Veteran (+50 Thn)";
    return "Veteran (30+ Thn)";
  }
  if (upper.includes("BOB") || upper.includes("BEST OF THE BEST")) return "Best of the Best";

  // Helper to map numeric age to standard Karate division label
  const getLabelFromAgeNumber = (age: number): string => {
    if (age <= 7) return "Pra Usia Dini (6-7 Thn)";
    if (age >= 8 && age <= 9) return "Usia Dini (8-9 Thn)";
    if (age >= 10 && age <= 11) return "Pra Pemula (10-11 Thn)";
    if (age >= 12 && age <= 13) return "Pemula (12-13 Thn)";
    if (age >= 14 && age <= 15) return "Kadet (14-15 Thn)";
    if (age >= 16 && age <= 17) return "Junior (16-17 Thn)";
    if (age >= 18 && age <= 20) return "U-21 (18-20 Thn)";
    if (age >= 21 && age <= 29) return "Senior (21+ Thn)";
    if (age >= 30 && age <= 40) return "Veteran (30-40 Thn)";
    if (age >= 41 && age <= 50) return "Veteran (40-50 Thn)";
    if (age > 50) return "Veteran (+50 Thn)";
    return `Usia ${age} Thn`;
  };

  // 2. Derive from birthDate if available
  if (birthDate) {
    const bYear = new Date(birthDate).getFullYear();
    const currentYear = new Date().getFullYear();
    const age = currentYear - bYear;
    if (age > 0 && age < 100) {
      return getLabelFromAgeNumber(age);
    }
  }

  // 3. Derive from minAge / maxAge if available
  if (minAge || maxAge) {
    const ageRef = minAge || maxAge || 0;
    if (ageRef > 0) {
      return getLabelFromAgeNumber(ageRef);
    }
  }

  return "Umum / Bebas";
}


