import type { LucideIcon } from "lucide-react";
import {
  Archive,
  ArrowLeftRight,
  Award,
  BadgeCheck,
  Banknote,
  Bell,
  BookOpen,
  Building,
  Building2,
  CalendarDays,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  FileEdit,
  FileSpreadsheet,
  FileText,
  FolderArchive,
  GraduationCap,
  Home,
  Images,
  Layers,
  LayoutDashboard,
  Mail,
  MapPin,
  MessageSquare,
  Newspaper,
  Notebook,
  Radio,
  ReceiptText,
  ScrollText,
  Settings,
  Shield,
  ShoppingBag,
  Sparkles,
  Swords,
  Trophy,
  User,
  UserCog,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";

const NAV_ICONS: Record<string, LucideIcon> = {
  // Admin — top-level
  "Beranda Admin": LayoutDashboard,
  Keanggotaan: Users,
  Sekretariat: ScrollText,
  "Iuran Anggota": Wallet,
  Keuangan: Banknote,
  Kas: CircleDollarSign,
  "Kwitansi Pembayaran": ReceiptText,
  Kwitansi: ReceiptText,
  Pembuatan: ReceiptText,
  Arsip: Archive,
  "UKT (Ujian Kenaikan Tingkat)": GraduationCap,
  "Latihan Bersama": Swords,
  "Kejuaraan / Pertandingan": Trophy,
  "Event & Kegiatan": CalendarDays,
  Laporan: FileSpreadsheet,
  Absensi: ClipboardCheck,
  Konten: Newspaper,
  Layanan: Layers,
  Sistem: Settings,
  Pengaturan: Settings,

  // Admin — children
  "Kelola Anggota": UserCog,
  Verifikasi: BadgeCheck,
  Organisasi: Building2,
  Pendaftaran: ClipboardList,
  "Pendaftaran & Roster": ClipboardList,
  "Kategori Kelas": Layers,
  "Arsip UKT": Archive,
  "Arsip Latihan Bersama": Archive,
  "Materi Digital": BookOpen,
  Store: ShoppingBag,
  Pesan: MessageSquare,
  "Carousel Beranda": Images,
  Apresiasi: Sparkles,
  Artikel: Newspaper,
  Notifikasi: Bell,
  "Kehadiran akun": Radio,
  "Log Audit": ScrollText,
  "Ringkasan Pengaturan": Settings,
  "Pengaturan Cabang": Building,
  "Pengaturan Ranting & User": UsersRound,
  "Profil & Kebijakan": FileText,
  "Pengaturan UKT": GraduationCap,
  "Role & Hak Akses": Shield,
  "Geofencing Absensi": MapPin,
  "Akun Saya": User,

  // Sekretariat children
  Dashboard: LayoutDashboard,
  "Surat & Persuratan": Mail,
  "Generator Surat": FileEdit,
  "Dokumen & SK": FolderArchive,
  "Notulen Rapat": Notebook,

  // Member dashboard
  Beranda: Home,
  "Profil Saya": User,
  Iuran: Wallet,
  "Kegiatan Saya": CalendarDays,
  "Pendaftaran Kejuaraan": Trophy,
  "Prestasi & Sabuk": Award,
  "Pindah Dojo": ArrowLeftRight,
  Dokumen: FileText,
};

export function getNavIcon(label: string): LucideIcon | null {
  return NAV_ICONS[label] ?? null;
}

