import type { LucideIcon } from "lucide-react";
import {
  Archive,
  ArrowLeftRight,
  Award,
  BadgeCheck,
  Bell,
  BookOpen,
  Building,
  Building2,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  FileText,
  GraduationCap,
  Home,
  Images,
  Layers,
  Newspaper,
  LayoutDashboard,
  MapPin,
  MessageSquare,
  Radio,
  ScrollText,
  Settings,
  Shield,
  ShoppingBag,
  Sparkles,
  Swords,
  User,
  UserCog,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";

const NAV_ICONS: Record<string, LucideIcon> = {
  // Admin — top-level
  "Beranda Admin": LayoutDashboard,
  Keanggotaan: Users,
  "Iuran Anggota": Wallet,
  "UKT (Ujian Kenaikan Tingkat)": GraduationCap,
  "Latihan Bersama": Swords,
  "Event & Kegiatan": CalendarDays,
  Absensi: ClipboardCheck,
  Konten: Newspaper,
  Layanan: Layers,
  Sistem: Settings,
  Pengaturan: Settings,

  // Admin — children
  "Kelola Anggota": UserCog,
  Verifikasi: BadgeCheck,
  Organisasi: Building2,
  Pendaftaran: ClipboardList,
  "Arsip UKT": Archive,
  "Arsip Latihan Bersama": Archive,
  "Materi Digital": BookOpen,
  Store: ShoppingBag,
  Pesan: MessageSquare,
  "Carousel Beranda": Images,
  Apresiasi: Sparkles,
  Artikel: Newspaper,
  Notifikasi: Bell,
  "Kehadiran akun": Radio,
  "Log Audit": ScrollText,
  "Ringkasan Pengaturan": Settings,
  "Pengaturan Cabang": Building,
  "Pengaturan Ranting & User": UsersRound,
  "Profil & Kebijakan": FileText,
  "Pengaturan UKT": GraduationCap,
  "Role & Hak Akses": Shield,
  "Geofencing Absensi": MapPin,
  "Akun Saya": User,

  // Member dashboard
  Beranda: Home,
  "Profil Saya": User,
  Iuran: Wallet,
  "Kegiatan Saya": CalendarDays,
  "Prestasi & Sabuk": Award,
  "Pindah Dojo": ArrowLeftRight,
  Dokumen: FileText,
};

export function getNavIcon(label: string): LucideIcon | null {
  return NAV_ICONS[label] ?? null;
}
